"use client"

import Link from "next/link"
import { SiteFooter } from "@/components/SiteFooter"
import { SiteHeader } from "@/components/SiteHeader"
import { useCart } from "@/components/useCart"
import { cartQuantity, cartTotalPaise, saveCart } from "@/lib/cart"
import { formatInr } from "@/lib/currency"

export default function CartPage() {
  const lines = useCart()
  const update = (productId: string, change: number) => saveCart(lines.map((line) => line.productId === productId ? { ...line, quantity: line.quantity + change } : line).filter((line) => line.quantity > 0))
  return <><SiteHeader /><main className="mx-auto max-w-5xl px-4 py-10 sm:px-6"><p className="text-sm font-bold uppercase tracking-[.18em] text-[#9b6411]">Your selection</p><h1 className="mt-2 text-3xl font-black text-[#43101c] sm:text-5xl">Enquiry cart</h1><p className="mt-4 max-w-2xl text-stone-600">Review each pack and quantity. Your final amount and availability are confirmed by Muniraj Crackers after you send the WhatsApp enquiry.</p>{!lines.length ? <section className="mt-8 rounded-3xl bg-white p-10 text-center shadow-sm"><p className="text-4xl">✦</p><h2 className="mt-4 text-xl font-black">Your cart is empty</h2><Link href="/catalogue" className="mt-6 inline-block rounded-xl bg-[#65162a] px-5 py-3 font-bold text-white">Browse catalogue</Link></section> : <><section className="mt-8 space-y-3">{lines.map((line) => <article key={line.productId} className="rounded-2xl border border-[#ead9b8] bg-white p-5"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-center"><div><h2 className="font-black text-[#43101c]">{line.titleSnapshot}</h2><p className="mt-1 text-sm text-stone-600">{line.packContentSnapshot}</p><p className="mt-2 text-sm font-bold text-[#65162a]">{formatInr(line.pricePaiseSnapshot)} each</p></div><div className="flex items-center gap-2"><button aria-label={`Decrease ${line.titleSnapshot} quantity`} onClick={() => update(line.productId, -1)} className="h-11 w-11 rounded-xl border border-stone-300 text-xl font-bold">−</button><span className="min-w-9 text-center font-black" aria-label={`${line.quantity} packs`}>{line.quantity}</span><button aria-label={`Increase ${line.titleSnapshot} quantity`} onClick={() => update(line.productId, 1)} className="h-11 w-11 rounded-xl border border-stone-300 text-xl font-bold">+</button><button onClick={() => saveCart(lines.filter((item) => item.productId !== line.productId))} className="ml-2 rounded-xl px-3 py-2 text-sm font-bold text-[#9c2436] underline">Remove</button></div></div><p className="mt-4 border-t border-stone-100 pt-3 text-right text-sm font-bold">Line estimate: {formatInr(line.pricePaiseSnapshot * line.quantity)}</p></article>)}</section><section className="mt-7 rounded-3xl bg-[#43101c] p-6 text-white"><div className="flex justify-between text-sm text-white/70"><span>{cartQuantity(lines)} packs selected</span><button onClick={() => saveCart([])} className="font-bold underline">Clear cart</button></div><div className="mt-5 flex items-end justify-between gap-4"><div><p className="text-sm text-white/70">Merchandise estimate</p><p className="text-3xl font-black">{formatInr(cartTotalPaise(lines))}</p></div><Link href="/enquiry" className="rounded-xl bg-[#e6aa30] px-5 py-3 text-center font-black text-[#321017]">Continue to enquiry</Link></div><p className="mt-4 text-xs text-white/70">Delivery, final availability and the final total are confirmed by the seller.</p></section></>}</main><SiteFooter /></>
}
