import Link from "next/link"
import { SiteFooter } from "@/components/SiteFooter"
import { SiteHeader } from "@/components/SiteHeader"
import { formatInr } from "@/lib/currency"
import { getCatalogue } from "@/lib/catalogue"

export default async function Home() {
  const { categories, products } = await getCatalogue()
  return <><SiteHeader /><main>
    <section className="bg-[#65162a] px-5 py-20 text-white sm:py-28"><div className="mx-auto max-w-5xl text-center"><p className="text-sm font-bold uppercase tracking-[.25em] text-[#f7d682]">Muniraj Crackers</p><h1 className="mt-5 text-4xl font-black tracking-tight sm:text-6xl">A simple way to build your celebration list.</h1><p className="mx-auto mt-6 max-w-2xl text-lg leading-8 text-white/80">Browse 51 categories, select quantities, and send one clear WhatsApp enquiry estimate to our team.</p><div className="mt-9 flex flex-col justify-center gap-3 sm:flex-row"><Link href="/catalogue" className="rounded-full bg-[#e6aa30] px-7 py-3.5 font-black text-[#371017]">Browse catalogue</Link><Link href="/safety" className="rounded-full border border-white/40 px-7 py-3.5 font-bold">Read safety guidance</Link></div><p className="mt-7 text-xs text-white/65">Enquiry estimates only. Availability, eligibility and final terms require seller confirmation.</p></div></section>
    <section className="mx-auto max-w-7xl px-5 py-16"><div className="flex items-end justify-between gap-5"><div><p className="text-sm font-bold uppercase tracking-[.18em] text-[#9b6411]">Explore</p><h2 className="mt-2 text-3xl font-black text-[#43101c]">Shop by category</h2></div><Link href="/catalogue" className="font-bold text-[#65162a] underline">View all</Link></div><div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{categories.slice(0, 8).map((category) => <Link key={category.id} href={`/catalogue/${category.slug}`} className="rounded-2xl border border-[#ead9b8] bg-white p-6 shadow-sm transition hover:-translate-y-1"><span className="text-3xl">✦</span><h3 className="mt-7 font-black text-[#43101c]">{category.title}</h3><p className="mt-2 text-sm text-stone-600">Explore products and pack estimates</p></Link>)}</div></section>
    <section className="bg-white px-5 py-16"><div className="mx-auto max-w-7xl"><p className="text-sm font-bold uppercase tracking-[.18em] text-[#9b6411]">Popular starting points</p><div className="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{products.slice(0, 4).map((product) => <Link key={product.id} href={`/catalogue/${product.categorySlug}/${product.slug}`} className="rounded-2xl border border-[#ead9b8] p-5"><p className="text-sm font-bold text-[#65162a]">{formatInr(product.pricePaise)}</p><h3 className="mt-2 font-black text-[#43101c]">{product.title}</h3><p className="mt-2 text-sm text-stone-600">{product.packContent}</p></Link>)}</div></div></section>
    <section className="mx-auto max-w-5xl px-5 py-16"><div className="rounded-3xl bg-[#fff0ca] p-8 text-center"><h2 className="text-2xl font-black text-[#43101c]">How enquiry works</h2><ol className="mt-6 grid gap-5 text-left sm:grid-cols-3"><li><b>1. Browse</b><br /><span className="text-sm text-stone-700">Find products and packs.</span></li><li><b>2. Add quantities</b><br /><span className="text-sm text-stone-700">Review a transparent estimate.</span></li><li><b>3. Send WhatsApp enquiry</b><br /><span className="text-sm text-stone-700">The seller confirms availability and final terms.</span></li></ol></div></section>
  </main><SiteFooter /></>
}
