import Link from "next/link"
import { SiteFooter } from "@/components/SiteFooter"
import { SiteHeader } from "@/components/SiteHeader"
import { formatInr } from "@/lib/currency"
import { getCatalogue } from "@/lib/catalogue"

export default async function Home() {
  const { categories, products } = await getCatalogue()
  return <><SiteHeader /><main>
    <section className="site-container grid min-h-[620px] items-center gap-10 py-16 lg:grid-cols-[1fr_.85fr] lg:py-10"><div><p className="festival-kicker flex items-center gap-3 before:h-px before:w-7 before:bg-[#f4b942] after:h-px after:w-7 after:bg-[#f4b942]">Diwali collection</p><h1 className="festival-heading mt-6 text-6xl font-black tracking-[-.075em] text-white sm:text-7xl lg:text-8xl">Celebrate <em>bigger.</em><br />Save more.</h1><p className="mt-5 text-sm text-[#dfb75c]">உங்கள் கொண்டாட்டத்திற்கு சிறப்பான பட்டாசுகள் — சிறந்த விலையில்!</p><p className="mt-5 max-w-xl text-base leading-7 text-[#a7a8bd]">A clear, festive catalogue for every celebration. Select packs as you browse and send your complete enquiry on WhatsApp in just two steps.</p><div className="mt-8 flex flex-wrap gap-3"><Link href="/catalogue" className="festival-button festival-button-gold">Explore products <span className="ml-2">→</span></Link><Link href="/about" className="festival-button festival-button-ghost">Our story</Link></div><div className="mt-10 flex gap-8 text-white"><div><p className="text-2xl font-black">{products.length}<span className="text-[#f4b942]">+</span></p><p className="mt-1 text-[10px] uppercase tracking-[.14em] text-[#a7a8bd]">Products</p></div><div><p className="text-2xl font-black">{categories.length}</p><p className="mt-1 text-[10px] uppercase tracking-[.14em] text-[#a7a8bd]">Categories</p></div><div><p className="text-2xl font-black">Easy</p><p className="mt-1 text-[10px] uppercase tracking-[.14em] text-[#a7a8bd]">Enquiry</p></div></div></div>
      <div className="relative grid min-h-[380px] place-items-center"><div className="absolute h-[300px] w-[300px] rounded-full border border-[#f4b942]/30 shadow-[0_0_70px_rgba(156,70,189,.22),inset_0_0_70px_rgba(255,173,57,.08)] sm:h-[380px] sm:w-[380px]" /><div className="absolute h-[220px] w-[220px] rounded-full border border-dashed border-[#f4b942]/25 sm:h-[280px] sm:w-[280px]" /><div className="relative grid aspect-[.77] w-40 place-items-center border border-[#f4b942] bg-gradient-to-br from-[#d23f35] via-[#641b4d] to-[#21133f] p-4 text-center shadow-[18px_25px_50px_rgba(0,0,0,.45)] rotate-[8deg] sm:w-48"><span className="text-5xl font-black tracking-[-.1em] text-[#f4b942]">MC</span><b className="text-lg leading-tight text-[#fff3cc]">Celebrate<br />in colour</b><small className="text-[7px] tracking-[.2em] text-[#f4b942]">PREMIUM COLLECTION</small></div><div className="absolute right-0 top-10 border border-white/10 bg-[#151331]/80 px-3 py-2 text-xs text-[#d8d5e3] backdrop-blur">✦ Made for moments</div><div className="absolute bottom-7 left-0 border border-white/10 bg-[#151331]/80 px-3 py-2 text-xs text-[#d8d5e3] backdrop-blur">★ Festive favourites</div></div>
    </section>
    <section className="border-y border-[#f4b942]/25 bg-[#f4b942]/[.055] py-4 text-center text-[11px] font-bold uppercase tracking-[.18em] text-[#f4b942]">More choices <span className="mx-6 text-[#ed7338]">✦</span> Better value <span className="mx-6 text-[#ed7338]">✦</span> உங்கள் கொண்டாட்டம். உங்கள் தேர்வு.</section>
    <section className="site-container py-24"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="festival-kicker">The collection</p><h2 className="festival-heading mt-3 text-5xl font-black text-white">Find your <em>spark.</em></h2></div><p className="max-w-sm text-sm leading-6 text-[#a7a8bd]">Every category is ready to browse in one uninterrupted order sheet.</p></div><div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{categories.slice(0, 8).map((category, index) => <Link key={category.id} href={`/catalogue/${category.slug}`} className="festival-card group min-h-52 p-6 transition hover:-translate-y-1 hover:border-[#f4b942]/50"><span className="text-6xl text-[#f4b942]/40">0{index + 1}</span><h3 className="mt-10 text-xl font-black text-white">{category.title}</h3><p className="mt-3 text-sm text-[#a7a8bd]">Explore packs and offer prices <span className="text-[#f4b942]">→</span></p></Link>)}</div><div className="mt-10 text-center"><Link href="/catalogue" className="festival-button festival-button-ghost">View all {products.length} products <span className="ml-2">→</span></Link></div></section>
    <section className="border-y border-white/[.07] bg-[#11122b] py-24"><div className="site-container grid gap-12 lg:grid-cols-[1fr_.8fr] lg:items-center"><div><p className="festival-kicker">Simple order flow</p><h2 className="festival-heading mt-3 text-5xl font-black text-white">Pick packs.<br /><em>Send one list.</em></h2><div className="mt-8 space-y-3">{[["1", "Select any packs", "Use the direct − 0 + controls as you browse."], ["2", "Review in the quick enquiry", "See your selected product list and total instantly."], ["3", "Open WhatsApp", "Review the prefilled message and send when ready."]].map(([number, title, detail]) => <div key={number} className="flex gap-4 border-b border-white/10 py-4"><span className="text-2xl font-black text-[#f4b942]">{number}</span><div><h3 className="font-bold text-white">{title}</h3><p className="mt-1 text-sm text-[#a7a8bd]">{detail}</p></div></div>)}</div></div><div className="festival-card relative overflow-hidden p-8"><div className="absolute -right-10 -top-10 h-48 w-48 rounded-full bg-[#ed7338]/20 blur-3xl" /><p className="festival-kicker">Popular starting points</p><div className="relative mt-5 space-y-3">{products.slice(0, 4).map((product) => <div key={product.id} className="flex items-center justify-between border-b border-white/10 py-3"><div><p className="font-bold text-white">{product.title}</p><p className="text-xs text-[#a7a8bd]">{product.packContent}</p></div><p className="font-black text-[#f4b942]">{formatInr(product.pricePaise)}</p></div>)}</div><Link href="/catalogue" className="festival-button festival-button-gold mt-7 w-full">Start selecting packs →</Link></div></div></section>
  </main><SiteFooter /></>
}
